language: node_js
node_js:
  - "lts/*"
services:
  - postgresql
cache: yarn
install: yarn
before_script:
  - psql -c 'create database hschat;' -U postgres
script:
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app: hsc-backend
  on: master
after_success: npm run coverage
